% REGEN_COMPARE_ESTIMATORS_OUTPUTS  Re-emit the compare_estimators .dat
% tables and .tex from the saved compare_estimators.mat (no resimulation).

here = fileparts(mfilename('fullpath'));
results_dir = fullfile(here, 'results');
if ~exist(results_dir, 'dir'); mkdir(results_dir); end
addpath(here);
cd(here);

R = load(fullfile(results_dir, 'compare_estimators.mat'));
methods    = R.methods;
estimators = R.estimators;

out_dir = fullfile(results_dir, 'pgfplots');
if ~exist(out_dir, 'dir'); mkdir(out_dir); end

for ie = 1:numel(estimators)
    method_idx = (1:numel(methods)).';
    rows = [method_idx, R.err_u_max(:,ie), R.err_u_avg(:,ie), ...
            R.err_sigma_r_max(:,ie), R.err_sigma_r_avg(:,ie), ...
            R.err_sigma_t_max(:,ie), R.err_sigma_t_avg(:,ie), ...
            R.wall(:,ie), R.ndof(:,ie), R.nel(:,ie)];
    write_dat(fullfile(out_dir, sprintf('compare_%s.dat', estimators{ie})), ...
              {'method_idx','err_u_max','err_u_avg', ...
               'err_sr_max','err_sr_avg','err_st_max','err_st_avg', ...
               'wall','ndof','nel'}, rows);
end

write_pgfplots(fullfile(out_dir, 'compare_estimators.tex'), methods, estimators);
fprintf('Regenerated %s and per-estimator .dat files.\n', ...
        fullfile(out_dir, 'compare_estimators.tex'));

% =========================================================================
function write_dat(filename, headers, data)
    fid = fopen(filename, 'w');
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s', headers{1});
    for k = 2:numel(headers); fprintf(fid, '\t%s', headers{k}); end
    fprintf(fid, '\n');
    fmt = [repmat('%.10g\t', 1, size(data, 2) - 1), '%.10g\n'];
    for i = 1:size(data, 1)
        fprintf(fid, fmt, data(i, :));
    end
end

function write_pgfplots(filename, methods, estimators)
    fid = fopen(filename, 'w');
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%% Auto-generated by regen_compare_estimators_outputs.m\n');
    fprintf(fid, '\\documentclass[tikz,border=4pt]{standalone}\n');
    fprintf(fid, '\\usepackage{pgfplots}\n');
    fprintf(fid, '\\pgfplotsset{compat=1.18, every axis/.append style={font=\\small}}\n\n');
    fprintf(fid, '\\begin{document}\n\n');

    metrics = {
        'err_u_max',  'Max $|u_r - u_\mathrm{Hill}|$',     'Max u-error';
        'err_u_avg',  'Avg $|u_r - u_\mathrm{Hill}|$',     'Avg u-error';
        'err_sr_max', 'Max $|\sigma_r - \sigma_r^\mathrm{Hill}|$ [MPa]', 'Max $\sigma_r$ error';
        'err_sr_avg', 'Avg $|\sigma_r - \sigma_r^\mathrm{Hill}|$ [MPa]', 'Avg $\sigma_r$ error';
        'err_st_max', 'Max $|\sigma_t - \sigma_t^\mathrm{Hill}|$ [MPa]', 'Max $\sigma_t$ error';
        'err_st_avg', 'Avg $|\sigma_t - \sigma_t^\mathrm{Hill}|$ [MPa]', 'Avg $\sigma_t$ error';
    };

    est_colors = {'blue!60!black', 'orange!80!black'};
    method_labels = cell(numel(methods), 1);
    for i = 1:numel(methods)
        method_labels{i} = sprintf('{%s}', strrep(methods{i}, '_', '\_'));
    end
    xticklabels_list = strjoin(method_labels, ',');

    for k = 1:size(metrics, 1)
        col  = metrics{k, 1};
        ylab = metrics{k, 2};
        ttl  = metrics{k, 3};

        fprintf(fid, '\\begin{tikzpicture}\n');
        fprintf(fid, '\\begin{axis}[\n');
        fprintf(fid, '  ybar, ymode=log, log origin=infty,\n');
        fprintf(fid, '  width=11cm, height=7cm, bar width=12pt,\n');
        fprintf(fid, '  xtick={1,2,3}, xticklabels={%s},\n', xticklabels_list);
        fprintf(fid, '  enlarge x limits=0.2,\n');
        fprintf(fid, '  ylabel={%s},\n', ylab);
        fprintf(fid, '  title={%s vs Hill, max\\_level = 3},\n', ttl);
        fprintf(fid, '  legend pos=outer north east, grid=both]\n');
        for ie = 1:numel(estimators)
            color = est_colors{1 + mod(ie - 1, numel(est_colors))};
            fprintf(fid, '\\addplot+[fill=%s, draw=%s] table[x=method_idx, y=%s] {compare_%s.dat};\n', ...
                    color, color, col, estimators{ie});
            fprintf(fid, '\\addlegendentry{%s}\n', strrep(estimators{ie}, '_', '\_'));
        end
        fprintf(fid, '\\end{axis}\n\\end{tikzpicture}\n\n');
    end

    fprintf(fid, '\\begin{tikzpicture}\n');
    fprintf(fid, '\\begin{axis}[\n');
    fprintf(fid, '  ybar, width=11cm, height=7cm, bar width=12pt,\n');
    fprintf(fid, '  xtick={1,2,3}, xticklabels={%s},\n', xticklabels_list);
    fprintf(fid, '  enlarge x limits=0.2,\n');
    fprintf(fid, '  ylabel={Wall-clock [s]},\n');
    fprintf(fid, '  title={Cost per (estimator, method), max\\_level = 3},\n');
    fprintf(fid, '  legend pos=outer north east, grid=both]\n');
    for ie = 1:numel(estimators)
        color = est_colors{1 + mod(ie - 1, numel(est_colors))};
        fprintf(fid, '\\addplot+[fill=%s, draw=%s] table[x=method_idx, y=wall] {compare_%s.dat};\n', ...
                color, color, estimators{ie});
        fprintf(fid, '\\addlegendentry{%s}\n', strrep(estimators{ie}, '_', '\_'));
    end
    fprintf(fid, '\\end{axis}\n\\end{tikzpicture}\n\n');

    fprintf(fid, '\\end{document}\n');
end
